language: php
php:
  - '5.5'

os:
  - linux

git:
  depth: 1

sudo: false

install:
  - composer install --no-interaction

notifications:
     email:
        on_success: always
        on_failure: always


