language: php

git:
  depth: 1

sudo: true

services:
  - elasticsearch


php:
  - '5.5'
  - '5.6.6'
  - '7.0'
  - '7.1'
  - '7.2'
  - '7.3'
  - '7.4'

os:
  - linux

install:
  - composer install --no-interaction
  - composer require satooshi/php-coveralls


before_script:
  - sleep 10


after_script:
  - travis_retry php vendor/bin/coveralls -v




