language: php
php:
  - '5.5'
  - '5.6'
  - '7.0'
  - '7.1'

os:
  - linux

services:
  - elasticsearch

before_install:
  - curl -O https://artifacts.elastic.co/downloads/elasticsearch/elasticsearch-5.3.1.deb && sudo dpkg -i --force-confnew elasticsearch-5.3.1.deb && sudo service elasticsearch restart

before_script:
  - sleep 10

git:
  depth: 1

sudo: false

install:
  - composer install --no-interaction

notifications:
     email:
        on_success: always
        on_failure: always


