language: php

git:
  depth: 1

sudo: true

php:
  - '5.5'
  - '5.6.6'
  - '7.0'
  - '7.1'
  - '7.2'
  - '7.3'
  - '7.4'

os:
  - linux

jdk:
  - oraclejdk8

addons:
  apt:
    packages:
        - oracle-java8-installer
env:
  global:
    - JAVA_HOME="/usr/lib/jvm/java-8-oracle/jre"

before_install:
  - sudo update-java-alternatives -s java-8-oracle
  - curl -O https://artifacts.elastic.co/downloads/elasticsearch/elasticsearch-5.1.1.deb && sudo dpkg -i --force-confnew elasticsearch-5.1.1.deb && sudo service elasticsearch restart

install:
  - composer install --no-interaction
  - composer require satooshi/php-coveralls


before_script:
  - sleep 10


after_script:
  - travis_retry php vendor/bin/coveralls -v




