language: php
php:
  - '5.5'
  - '5.6'
  - '7.0'
  - '7.1'

os:
  - linux

services:
  - elasticsearch

before_script:
  - sleep 20

git:
  depth: 1

sudo: false

install:
  - composer install --no-interaction

notifications:
     email:
        on_success: always
        on_failure: always


